### ISSUE TITLE
 As a CB employee I can view a specific users details

### ISSUE THREAD

**Issue by RogeredBacon** [FAC-11/DataPower#121]
1 Day

References #123 

I guess we may want to display their QR code on this page?

**Comment by finnhodgkin** [comment]
I'm not sure if this issue is actually addressed yet #172 

Although you can access an individual users page, at the moment the only way to get there is through the users dashboard. If there were thousands of users in a community business it would be really hard to sift through the list to find a single user. 

We should probably add a user search route.

**Comment by finnhodgkin** [comment]
I'm not sure if this issue is actually addressed yet #172 

Although you can access an individual users page, at the moment the only way to get there is through the users dashboard. If there were thousands of users in a community business it would be really hard to sift through the list to find a single user. 

We should probably add a user search route.

**Comment by RogeredBacon** [comment]
Should we keep this open or go with the more specific issues, addressing the same things above?

**Comment by RogeredBacon** [comment]
Closing this because of the more specific issue
