### ISSUE TITLE
After multiple scans it doesn't always return a username

### ISSUE THREAD

**Issue by RogeredBacon** [FAC-11/DataPower#71]
- [ ] Stops getting the correct username from the database using the hash.

**Comment by ZooeyMiller** [comment]
Does this problem occur when scanning the same code multiple times, or when scanning different codes? If you give me some kind of admin login I can attempt to recreate the bug and see what's happening.

**Comment by ZooeyMiller** [comment]
Not sure if this is to do with the problem, but assuming the relevant file for this stuff is `qrcode.js` 

from line 21: 
```js
function instascan() {
  return new Promise((resolve, reject) => {
    let scanner = new Instascan.Scanner({
      video: document.getElementById('preview'),
      scanPeriod: 5,
    });
    scanner.addListener('scan', function(content) {
      if (document.getElementById('preview')) {
        document.getElementById('preview').pause();
      }
      resolve(content);
    });
    Instascan.Camera
      .getCameras()
      .then(cameras => {
        if (cameras.length > 0) {
          scanner.start(cameras[0]);
        } else {
          console.error('No cameras found.');
        }
      })
      .catch(err => {
        console.error(err);
      });
  });
}
```
you are returning a promise which doesn't reject. ideally you should add reject somewhere in case something doesn't go to plan. It means this function doesn't really have any error handling.

**Comment by azayneeva** [comment]
@ZooeyMiller , 

> If you give me some kind of admin login

What kind of admin login do you mean? 
To recreate this bug you can register with the app and make a picture of a qr code that will be generated for you. And then try to login with this qr code many times, after a while you won't be able to see your username when you log in. 

And good find with the promise, we'll add reject, we should have done this before. We'll check if this helps.

**Comment by ZooeyMiller** [comment]
@azayneeva Sorry I think I was confused on how to recreate this bug, I'll try again to see if I can find any kind of problem.

**Comment by ZooeyMiller** [comment]
Separate problem, but found when looking, in `qrcode.js` when you set `activity` as the key on the list of activities, as activity is an object, it is being coerced to a string as `[object Object]` meaning the keys are not unique, leading to this error. 


![screenshot from 2017-11-10 12-45-11](https://user-images.githubusercontent.com/21139983/32655179-41605616-c615-11e7-8a6a-538a2da56126.png)

this could be remedied by setting the key to `activity.name` if name will always be unique to each activity, or just anything that can be guaranteed to be unique and consistent, so that react can use the key internally properly.

**Comment by ZooeyMiller** [comment]
So this is the error I'm getting in the console when I recreate the bug:

![screenshot from 2017-11-10 12-52-50](https://user-images.githubusercontent.com/21139983/32655466-460d8a20-c616-11e7-804f-98ddead6b99a.png)

The fact that it says "uncaught" makes me think it's something related to promises, is this the same error you are getting?

**Comment by ZooeyMiller** [comment]
First thing I notice is that it always happens on the 3rd scan, so at least it's consistent. 

Also, there are a lot of promises without error handling in this file, my first step for you both would for every promise that doesn't have a `.catch` (in the whole project) add one in. I feel like we might be able to solve this bug by adding error handling everywhere that it doesn't already exist. 

Still looking into root cause of bug though. 

(I'm just going to keep track of all of my thoughts in comments on this issue)

**Comment by ZooeyMiller** [comment]
from looking a lot and `console.log`ging in quite a few places, it seems the problem is that the `scan` event on your QR scanner is running without anything being scanned. 
So it's running that scan event, but without the hash from the QRcode, so it can't get any meaningful information. 

![screenshot from 2017-11-10 13-52-34](https://user-images.githubusercontent.com/21139983/32657436-6c715946-c61e-11e7-8a2e-90d60e7508cf.png)

From this screenshot you can see that I'm on the second stage of login, but from React devtools on the right you can see that the user's information hasn't been put into state. We'll need to look more into why this is happening, but I think this is where the error is happening.

If you scan a user, then a different user, then the first user again (and so on) does the error still happen? Or is it only when the same user it repeatedly, consecutively scanned?

**Comment by ZooeyMiller** [comment]
Okay, I've made a fix that's in the [fix-scan-bug](https://github.com/FAC-11/DataPower/tree/fix-scan-bug) branch. 

The main thing that was needed was needed was to call `scanner.stop()` when you've finished scanning each time. 

Please take a look at this code, make sure it works on your local machines, then look at fixing the error handling in this file, so that it's a little more meaningful, and make a PR, assigning me and adding me as a reviewer.
